language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install gdal-bin libgdal-dev 
install:
  - "pip install -r requirements.txt"
  - "pip install py.test"
  - "python setup.py develop"
script: py.test -k 'not test_filter_vsi'
