language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.3"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install libgdal-dev 
install:
  - "pip install -r requirements.txt"
  - "python setup.py develop"
script: nosetests
