language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get build-dep gdal
  - . ./scripts/travis_gdal_install.sh
install:
  - "pip install -r requirements-dev.txt"
  - "pip install pytest"
  - "pip install coveralls"
  - "pip install --global-option=build_ext --global-option='-I$HOME/gdal/include' --global-option='-L$HOME/gdal/lib' --global-option='-lgdal' -e ."
script: 
  - nosetests --exclude test_filter_vsi --exclude test_geopackage
  - coverage run --source=fiona --omit='*.pxd,*.pyx,*/tests/*,*/docs/*,*/examples/*,*/benchmarks/*' -m nose --exclude test_filter_vsi --exclude test_geopackage
after_success:
  - coveralls
env:
#  - GDALVERSION="1.9.2"
  - GDALVERSION="1.11.2"
#  - GDALVERSION="2.0.0"
cache:
  directories:
    - $HOME/gdalbuild/gdal-1.9.2
    - $HOME/gdalbuild/gdal-1.11.2
    - $HOME/gdalbuild/gdal-2.0.0
